import type { DashboardData } from "./crm-types";

export const seedMarginPolicy = {
  byChannel: {
    OWN_MALL: { totalMarginRate: 18, sellerMarginRate: 10 },
    SELLER_MALL: { totalMarginRate: 14, sellerMarginRate: 8 },
    BRAND_MALL: { totalMarginRate: 12, sellerMarginRate: 7 },
  },
  slides: [
    { minActualSales: 30000000, totalMarginAddRate: 5, sellerMarginAddRate: 2 },
    { minActualSales: 50000000, totalMarginAddRate: 8, sellerMarginAddRate: 3 },
  ],
};

export const mockDashboardData: DashboardData = {
  deals: [
    {
      id: "deal-glow-ampoule",
      dealName: "코링코 글로우 앰플 4차 공구",
      brandName: "CORINGCO",
      costPrice: 16800,
      sellingPrice: 23900,
      status: "ARCHIVED",
      partner: { id: "partner-coringco", name: "CORINGCO", type: "BRAND" },
      baseMarginPolicy: seedMarginPolicy,
    },
    {
      id: "deal-wellness-pack",
      dealName: "뉴트리원 데일리 웰니스 패키지",
      brandName: "Nutrione",
      costPrice: 24500,
      sellingPrice: 35900,
      status: "NEGOTIATING",
      partner: { id: "partner-nutrione", name: "Nutrione", type: "VENDOR" },
      baseMarginPolicy: {
        byChannel: {
          OWN_MALL: { totalMarginRate: 16, sellerMarginRate: 9 },
          SELLER_MALL: { totalMarginRate: 13, sellerMarginRate: 8 },
          BRAND_MALL: { totalMarginRate: 11, sellerMarginRate: 6 },
        },
        slides: [{ minActualSales: 25000000, totalMarginAddRate: 4 }],
      },
    },
  ],
  sellers: [
    {
      id: "seller-mina",
      name: "Mina",
      snsType: "INSTAGRAM",
      snsHandle: "mina.market",
      currentFollowers: 128400,
      category: "Beauty",
      histories: [
        { snapshotDate: "2026-04-01", followersCount: 119000 },
        { snapshotDate: "2026-04-08", followersCount: 121500 },
        { snapshotDate: "2026-04-15", followersCount: 124200 },
        { snapshotDate: "2026-04-22", followersCount: 126800 },
        { snapshotDate: "2026-04-29", followersCount: 128400 },
      ],
    },
    {
      id: "seller-jun",
      name: "Jun Home",
      snsType: "YOUTUBE",
      snsHandle: "junhome",
      currentFollowers: 84200,
      category: "Living",
      histories: [
        { snapshotDate: "2026-04-01", followersCount: 80100 },
        { snapshotDate: "2026-04-08", followersCount: 81400 },
        { snapshotDate: "2026-04-15", followersCount: 82800 },
        { snapshotDate: "2026-04-22", followersCount: 83700 },
        { snapshotDate: "2026-04-29", followersCount: 84200 },
      ],
    },
  ],
  campaigns: [
    {
      id: "camp-glow-mina",
      dealId: "deal-glow-ampoule",
      sellerId: "seller-mina",
      campaignName: "코링코 글로우 앰플 4차 공구 Mina",
      dealName: "코링코 글로우 앰플 4차 공구",
      partnerName: "CORINGCO",
      sellerName: "Mina",
      snsType: "INSTAGRAM",
      snsHandle: "mina.market",
      startDate: "2026-05-04",
      endDate: "2026-05-10",
      salesChannel: "OWN_MALL",
      baseNaverLink: "https://brand.example.com/products/glow-ampoule",
      generatedTrackingLink:
        "https://brand.example.com/products/glow-ampoule?nt_source=INSTAGRAM&nt_medium=seller-mina&nt_detail=camp-glow-mina",
      actualSales: 41200000,
      totalMarginRate: 23,
      sellerMarginRate: 12,
      netMarginRate: 11,
      status: "ACTIVE",
      isManualMargin: false,
      assignedTo: null,
      updatedAt: "2026-05-03T08:30:00.000Z",
      followerHistory: [
        { date: "04-01", followers: 119000 },
        { date: "04-08", followers: 121500 },
        { date: "04-15", followers: 124200 },
        { date: "04-22", followers: 126800 },
        { date: "04-29", followers: 128400 },
      ],
      activityHistory: [
        {
          id: "activity-glow-created",
          action: "CREATED",
          label: "Campaign created",
          details: "ACTIVE · OWN_MALL",
          actor: "SYSTEM",
          createdAt: "2026-04-30T09:00:00.000Z",
        },
        {
          id: "activity-glow-sales",
          action: "ACTUAL_SALES_UPDATED",
          label: "Actual sales updated",
          details: "41,200,000 · auto margin recalculated",
          actor: "SYSTEM",
          createdAt: "2026-05-03T08:30:00.000Z",
        },
      ],
      notes: [],
    },
    {
      id: "camp-wellness-jun",
      dealId: "deal-wellness-pack",
      sellerId: "seller-jun",
      campaignName: "뉴트리원 데일리 웰니스 패키지 Jun Home",
      dealName: "뉴트리원 데일리 웰니스 패키지",
      partnerName: "Nutrione",
      sellerName: "Jun Home",
      snsType: "YOUTUBE",
      snsHandle: "junhome",
      startDate: "2026-05-15",
      endDate: "2026-05-21",
      salesChannel: "BRAND_MALL",
      baseNaverLink: "https://brand.example.com/wellness?ref=home",
      generatedTrackingLink:
        "https://brand.example.com/wellness?ref=home&nt_source=YOUTUBE&nt_medium=seller-jun&nt_detail=camp-wellness-jun",
      actualSales: null,
      totalMarginRate: 11,
      sellerMarginRate: 6,
      netMarginRate: 5,
      status: "PREPARATION",
      isManualMargin: false,
      assignedTo: null,
      updatedAt: "2026-04-28T10:00:00.000Z",
      followerHistory: [
        { date: "04-01", followers: 80100 },
        { date: "04-08", followers: 81400 },
        { date: "04-15", followers: 82800 },
        { date: "04-22", followers: 83700 },
        { date: "04-29", followers: 84200 },
      ],
      activityHistory: [
        {
          id: "activity-wellness-created",
          action: "CREATED",
          label: "Campaign created",
          details: "PREPARATION · BRAND_MALL",
          actor: "SYSTEM",
          createdAt: "2026-04-28T10:00:00.000Z",
        },
      ],
      notes: [],
    },
  ],
  apiCallLogs: [
    {
      id: "log-meta-1",
      provider: "INSTAGRAM",
      permissionScope: "instagram_basic",
      endpoint: "/mock/instagram/business_discovery",
      statusCode: 200,
      success: true,
      calledAt: "2026-05-01T09:00:00.000Z",
    },
    {
      id: "log-youtube-1",
      provider: "YOUTUBE",
      permissionScope: "youtube.readonly",
      endpoint: "/mock/youtube/channels",
      statusCode: 200,
      success: true,
      calledAt: "2026-05-01T09:05:00.000Z",
    },
  ],
  assets: [
    {
      id: "asset-glow-intro",
      provider: "GOOGLE_DRIVE",
      section: "PRODUCT_INTRO",
      entityType: "CAMPAIGN",
      entityId: "camp-glow-mina",
      campaignId: "camp-glow-mina",
      fileName: "코링코_글로우앰플_상품소개서.pdf",
      mimeType: "application/pdf",
      sizeBytes: 6_200_000,
      externalFileId: "drive-seed-glow-intro",
      externalUrl: "https://drive.google.com/file/d/drive-seed-glow-intro/view",
      notes: "브랜드사 전달 최신본",
      archivedAt: null,
      createdAt: "2026-05-01T10:00:00.000Z",
    },
    {
      id: "asset-glow-price",
      provider: "SUPABASE",
      section: "GROUP_BUY_PRICE",
      entityType: "CAMPAIGN",
      entityId: "camp-glow-mina",
      campaignId: "camp-glow-mina",
      fileName: "4차_공구단가표.xlsx",
      mimeType:
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      sizeBytes: 420_000,
      storagePath:
        "CAMPAIGN/코링코 글로우 앰플 4차 공구-camp-glow-mina/GROUP_BUY_PRICE/20260501_4차_공구단가표.xlsx",
      notes: "정산 전 확인 필요",
      archivedAt: null,
      createdAt: "2026-05-01T11:00:00.000Z",
    },
  ],
  storage: {
    supabaseLimitBytes: 1024 * 1024 * 1024,
    supabaseWarningBytes: 800 * 1024 * 1024,
    supabaseEstimatedBytes: 420_000,
    googleDriveConnected: false,
    googleDriveAccount: null,
    googleDriveRootFolderId: null,
    recentAssets: [],
  },
};

mockDashboardData.storage.recentAssets = mockDashboardData.assets;
