-- Enable Row Level Security on all public tables (Supabase Data API lockdown).
--
-- 배경: 이 프로젝트는 데이터 접근을 전적으로 Prisma(postgres role, 직결/풀러)로 하고,
-- Supabase 클라이언트는 Auth(auth 스키마)·Storage(storage 스키마)에만 쓴다. public 테이블을
-- PostgREST(.from/.rpc)로 읽는 코드는 0건이다. 그런데 RLS가 꺼져 있어 공개된 anon 키
-- (NEXT_PUBLIC_, 브라우저 번들에 실려 사실상 공개)로 Data API가 public 테이블을 그대로
-- 읽을 수 있었다(실측: Seller 전량 조회 성공). PUBLIC 레포 프로젝트라 노출 위험이 크다.
--
-- 조치: 모든 public 테이블에 RLS를 켠다. 정책(policy)을 하나도 만들지 않으면 anon·authenticated
-- 롤은 전부 거부된다 → Data API 노출이 닫힌다. Prisma가 쓰는 postgres 롤은 테이블 소유자이자
-- BYPASSRLS라 RLS의 영향을 받지 않고, service_role도 우회한다 → 앱 동작 무변화.
-- (FORCE 는 쓰지 않는다 — 소유자까지 RLS 대상이 되어 Prisma 경로를 깰 수 있다.)

ALTER TABLE "Partner" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Seller" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SellersHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SellerProfileBioHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Deal" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SalesCampaign" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CampaignBuyerFingerprint" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CampaignGroup" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CampaignChecklistTemplate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CampaignChecklistItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PartnerContact" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CampaignActivity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CampaignNote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Asset" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StorageIntegration" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ApiCallLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TrackingAttribution" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ActivityLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CampaignTemplate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SellerOutreach" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SalesTask" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SettlementChecklist" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SettlementChecklistItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Comment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReminderSettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RevenueGoal" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ImportBatch" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ImportSourceRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ChannelFeeConfig" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SellerCategory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SellerCategoryAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CampaignDeal" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SystemSettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrderCampaign" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DailyOrderTask" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TaskLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductMapping" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NaverOrderSnapshot" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrderFulfillmentState" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PriceMonitorSnapshot" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ActionProposal" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ActionProposalEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AssistantConversation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AssistantChatMessage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WorkRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ChatRoomMapping" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PriceSheet" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PriceSheetRow" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SellerAiProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReferenceInboxItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NaverSettlementCase" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrderActionLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SystemTaskStatus" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SystemTaskLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SellerStorySnapshot" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SellerPostClassification" ENABLE ROW LEVEL SECURITY;
